#===================================================================================
# https://github.com/ccccmagicboy/Marlin_fw_action
# Description: Build Marlin firmware using GitHub Actions.
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: MARLIN_BUILD

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_Marlin_v2.yml'
    - '!**.md'
  schedule:
    - cron: 0 9 * * *
  # watch:
    # types: [started]
    
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *    

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build
    
    env:
      REPO_URL: https://github.com/MarlinFirmware/Marlin.git
      
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        branch:
        - 2.0.x
        - 1.1.x
        - bugfix-2.0.x
        - bugfix-1.1.x
        - dev-2.1.x
        
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2
      
    - name: Clone the Marlin source code
      run: git clone --depth 1 $REPO_URL -b ${{ matrix.branch }} my_marlin
      
    - name: Install PlatformIO Core
      run: |
        pip install --upgrade pip
        pip install -U platformio
        python -m platformio --version
        
    - name: Install PlatformIO Core
      working-directory: my_marlin
      run: |
        python -m platformio run
        
        
        