#===================================================================================
# https://github.com/ccccmagicboy/Marlin_fw_action
# Description: Build Marlin v2 firmware using GitHub Actions.
# Lisence: MIT
# Author: ccccmagicboy
# Url: https://ccrobot-online.com
#===================================================================================

name: MARLIN2_BUILD

on:
  push:
    branches:
    - master
    paths:
    - '.github/workflows/build_for_Marlin_v2.yml'
    - '!**.md'
  schedule:
    - cron: 0 9 * * *
  # watch:
    # types: [started]
    
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of the month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12 or JAN-DEC)
# │ │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
# │ │ │ │ │                                   
# │ │ │ │ │
# │ │ │ │ │
# * * * * *    

env:
  TZ: Asia/Shanghai

jobs:
  build:
    name: Build Official
    
    env:
      REPO_URL: https://github.com/MarlinFirmware/Marlin.git
      
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        branch:
        - 2.0.x
        - bugfix-2.0.x
        
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2
      
    - name: Clone the Marlin source code
      run: git clone --depth 1 $REPO_URL -b ${{ matrix.branch }} my_marlin
      
    - name: Install PlatformIO Core
      run: |
        pip install --upgrade pip
        pip install -U platformio
        python -m platformio --version
        
    - name: Complie the Marlin
      working-directory: my_marlin
      run: |
        python -m platformio run --help
        python -m platformio run
        ls -al
        cd .pio
        ls -al
        cd build
        ls -al
        cd mega2560
        ls -al
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai' 
        
    - name: Get the string
      id: get_string
      uses: ccccmagicboy/get_branch_str@master
      with:
        in_str: ${{ matrix.branch }}
        
    - name: Zip the artifact
      working-directory: ./
      run: |
        zip --junk-paths ${{ steps.get_string.outputs.str }}_fw_${{ steps.get_datetime.outputs.datetime_str }} my_marlin/.pio/build/mega2560/firmware.hex README.md
        
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.get_string.outputs.str }}_fw_${{ steps.get_datetime.outputs.datetime_str }}
        path: ${{ steps.get_string.outputs.str }}_fw_${{ steps.get_datetime.outputs.datetime_str }}.zip

        
  build_2:
  
    name: Build self-host
    
    env:
      REPO_URL: https://github.com/ccccmagicboy/Marlin.git
      
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        branch:
        - ender3_cccc
        test-platform:
        - sanguino1284p
        
    steps:
    - name: Checkout this repos
      uses: actions/checkout@v2
      
    - name: Clone the Marlin source code
      run: git clone --depth 1 $REPO_URL -b ${{ matrix.branch }} my_marlin
      
    - name: Select Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7' # Version range or exact version of a Python version to use, using semvers version range syntax.
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified      
      
    - name: Install PlatformIO
      run: |
        pip install -U https://github.com/platformio/platformio-core/archive/master.zip
        platformio update
        platformio --version
        
    - name: Run ${{ matrix.test-platform }} Tests
      working-directory: ./my_marlin/
      run: |
        chmod +x buildroot/bin/*
        chmod +x buildroot/share/tests/*
        export PATH=./buildroot/bin/:./buildroot/share/tests/:${PATH}
        run_tests . ${{ matrix.test-platform }}
        
    - name: Complie the Marlin
      working-directory: my_marlin
      run: |
        platformio run -e ${{ matrix.test-platform }}
        cd .pio/build/${{ matrix.test-platform }}
        ls -al
        
    - name: Get the datetime
      id: get_datetime
      uses: ccccmagicboy/get_datetime@master
      with:
        tz1: 'Asia'
        tz2: 'Shanghai' 
        
    - name: Get the string
      id: get_string
      uses: ccccmagicboy/get_branch_str@master
      with:
        in_str: ${{ matrix.branch }}
        
    - name: Zip the artifact
      working-directory: ./
      run: |
        zip --junk-paths ${{ steps.get_string.outputs.str }}_fw_${{ steps.get_datetime.outputs.datetime_str }} my_marlin/.pio/build/${{ matrix.test-platform }}/firmware.hex README.md
        
    - name: Upload the zip file
      uses: actions/upload-artifact@master
      with:
        name: ${{ steps.get_string.outputs.str }}_fw_${{ steps.get_datetime.outputs.datetime_str }}
        path: ${{ steps.get_string.outputs.str }}_fw_${{ steps.get_datetime.outputs.datetime_str }}.zip

        
        